### ISSUE TITLE
Memory adapter with Loro fails.

### ISSUE THREAD

**Issue by jamesgibson14** [maxnowack/signaldb#1132]
I am playing around with [Loro ](https://loro.dev/) as a memory adapter and CRDT sync tool. The problem is in `getItemAndIndex` it calls `this.memory()` and since Loro saves data in WASM, each time it is called the object reference is different so doc never equals item `this.memory().findIndex(doc => doc === item)`.  It would probably work with an id comparison `doc => doc.id === item.id`

https://github.com/maxnowack/signaldb/blob/e184e2b00db1a5b432e5a80ada035d530166b534/packages/signaldb/src/Collection/index.ts#L360

**Comment by jamesgibson14** [comment]
After thinking about this more, I don't know if Loro will be a good memoryAdapter because incoming syncs to Loro wouldn't emit any of the SignalDB events.  I am going to try using it just as the sync engine and have it feed SignalDB

**Comment by maxnowack** [comment]
Interesting use case!
I think maybe it's better to implement it as a persistence adapter instead of a memory adapter

**Comment by jamesgibson14** [comment]
Closing.
