### ISSUE TITLE
Next.Js 15, fs error

### ISSUE THREAD

**Issue by maxpowernz** [maxnowack/signaldb#1142]
Followed the react instructions using NextJs and getting node filesystem errors, assume the imports are not working correctly somewhere.

./node_modules/.pnpm/signaldb@0.22.0/node_modules/signaldb/dist/index.mjs

 await (await import("fs")).promises.writeFile(t, n(l));

I was just browsing the library and this was the first experience with it. I don't have time to debug, but not a good first impression.

Cheers.

**Comment by maxnowack** [comment]
Hi @maxpowernz, could you please post the full log output where the error occurs? I'll take a look into it

**Comment by maxnowack** [comment]
Fix released with `v0.23.0` 🎉

**Comment by maxpowernz** [comment]
Hi Max, was completely my fault sorry, I wasn't resolving the fs in the next.config file. But, I switched to using --turbo (npm run --turbo) and that configuration is no longer needed with turbo, and turbo pack is super fast. Also dont need to dynamic import the index file either.
Cheers.

**Comment by maxpowernz** [comment]
Just a thought though, wouldnt it be better to warn rather than throw error if it does detect browser and not use fs at all?

**Comment by maxnowack** [comment]
I think if we just warn, we have to have a fallback behavior. I'm not sure what's most intuitive.
Automatically use local storage? Not perform persistence at all?

Throwing the error is the most explicit and lets the user decide what to do. This error doesn't occur often either.
