### ISSUE TITLE
Deep Clone Fail in Update Operation

### ISSUE THREAD

**Issue by SemAiSoft** [maxnowack/signaldb#1180]
Hello everyone!

Update on collection is failing when a  DOM element is involved in the object being updated. Basically, inserting works fine, but not  updating.
Of course, cloning DOM elements takes extra care. 

Please can it be attended to OR is there workaround until fix? Thanks.

**Comment by maxnowack** [comment]
I don't think that it's necessary nor a good idea to save DOM elements in a data structure and render them later on (reminds me a bit on the old jQuery times 😀).
I think it would be better to save some metadata that you need for positioning your elements (like x, y, height, etc.). Where you render the elements, you only use this data, but create new DOM elements everytime.

**Comment by SemAiSoft** [comment]
> I don't think that it's necessary nor a good idea to save DOM elements in a data structure and render them later on (reminds me a bit on the old jQuery times 😀). I think it would be better to save some metadata that you need for positioning your elements (like x, y, height, etc.). Where you render the elements, you only use this data, but create new DOM elements everytime.

😀😀😀 Super Funny. JQuery!
Anyways, though I don't need those data in my case: U have certainly opened up my Chi Pathways! I know what to do now. 
And thanks for support and the great SignalDb.

**Comment by maxnowack** [comment]
Great to hear! Thanks! 😀 
Then let's close this issue 🙂
