### ISSUE TITLE
Has Anyone Found Solution To This Bug!

### ISSUE THREAD

**Issue by SemAiSoft** [maxnowack/signaldb#1207]
This `fs module` error has kept me away from using this wonderful Library since its version 0.23.0. It won't allow project or library build.
I am on a fresh Angular 18 esbuild (vite) project, stil errors as shown below:

![Screenshot from 2024-12-10 00-12-16](https://github.com/user-attachments/assets/acfe07a7-d9da-4377-a840-f12fcd79bdc5)

**Comment by maxnowack** [comment]
It seems your screenshot upload wasn't complete at the time you posted your comment.
Do you mean the same issue as in #988? Could you provide a minimal reproduction repo?

**Comment by SemAiSoft** [comment]
> It seems your screenshot upload wasn't complete at the time you posted your comment. Do you mean the same issue as in #988? Could you provide a minimal reproduction repo?

Sorry, I just fixed the screenshot. ANd yes, as in issue #988 - just that this is not warning but an error stopping project build.

**Comment by maxnowack** [comment]
Your screenshot indicates that you use the filesystem persistence adapter somewhere on client side. Could you provide some code where you initialize your collection and adapters?

**Comment by SemAiSoft** [comment]
> Your screenshot indicates that you use the filesystem persistence adapter somewhere on client side. Could you provide some code where you initialize your collection and adapters?


My code in Angular service is as simple as below, meanwhile I try a Stabliz repro and get back to. THANKS.
```
@Injectable({
    providedIn: 'root'
})
export class DesignStoreService{
    readonly store: Collection<ICDesignData>;
    userProjects: ICDesignData[] = [];

    constructor() {  
            
        this.store = new Collection({
            persistence: createLocalStorageAdapter('cdesign-store'),
            reactivity: angularReactivityAdapter,
            indices: [
                createIndex('id'),
                createIndex('userId'),
            ]
        });

    }
}
```

**Comment by SemAiSoft** [comment]
> Your screenshot indicates that you use the filesystem persistence adapter somewhere on client side. Could you provide some code where you initialize your collection and adapters?

Well, I have found a work around in the meantime until fix, or browser browser file to import. The fix is the option:

`"externalDependencies": ["fs"]`

in build section of Angular/project .json. 
Smiles, I just prefer this project over Dexie, RxDb, etc. Far simpler, cleaner and straightforward in its implementation.
Thanks for the Good Work.

**Comment by maxnowack** [comment]
I see. Then let's close this one a it is the same issue as discussed in #988. I'm currently preparing `v1.0.0` which splits out the persistence adapters and therefore eliminates this error 🙂 
Thanks!
