### ISSUE TITLE
Reactivity in React.

### ISSUE THREAD

**Issue by yaldram** [maxnowack/signaldb#463]
I am using `signal db` with react, I have one collection defined as follows - 
```ts
import { PersistentCollection } from 'signaldb'

export const collectionChats = new PersistentCollection('collection-chats')
```
I am consuming this collection in a nested route, in my application and I have a delete chats button on the main route, when I delete the chats in the main route, my nested route component is not re-rendering here is the code for my main route - 
```tsx
return (
    <div className="w-full p-9 pb-0 flex flex-col gap-4 h-full">
      <div className="flex justify-between">
        <Tabs defaultValue="account" className="w-[400px]">
          <TabsList className="grid w-full grid-cols-2">
            <NavLink to="videos">
              Videos
            </NavLink>
            <NavLink to="videos/chat">
              Chat
            </NavLink>
          </TabsList>
        </Tabs>
        <Button
          onClick={() => {
            collectionChats.updateOne(
              { id: params.collectionId },
              {
                $set: { chats: [] },
              }
            );
          }}
          variant="destructive"
        >
          <Trash2Icon className="h-[1.2rem] mr-2 w-[1.2rem] dark:-bg-white bg-dark" /> Delete Chat
        </Button>
      </div>

      <div className="w-full h-full pb-4 overflow-hidden">
        <Outlet />
      </div>
    </div>
  );
```
I am consuming the `collectionChats` inside the chat route which is a nested route - 
```tsx
const chatMessages = collectionChats.findOne({ id: params.collectionId });
```

I am expecting that when I click on the delete button and set the chats array to empty for a particular collectionId, my chat route should re-render and all the chats should disappear.

**Comment by yaldram** [comment]
Also one issue that I noticed is that when I navigate away from the chat route, where I am using the `collectionChats` - 
```ts
 const chatMessages = collectionChats.findOne({ id: params.collectionId });
```
I see a basic console.log statement even when I am navigating away from the route.

Below is SCREE ONE  - 
<img width="1396" alt="image" src="https://github.com/maxnowack/signaldb/assets/13429535/36ad0d04-be27-479b-be4c-3422fa779c93">

Below is SCREEN TWO - 
<img width="1396" alt="image" src="https://github.com/maxnowack/signaldb/assets/13429535/38533647-0899-4189-b750-ba9afa2f4199">

**Comment by yaldram** [comment]
I also tried with using an `effect` from `'@maverick-js/signals` but no luck.

**Comment by yaldram** [comment]
Also try a simple `console.log` in your route and move away from that route, the console.log is printed even when you move away from the route.

**Comment by maxnowack** [comment]
Hey @yaldram, the data fetching must run in a reactive context to be reactive (`effect()` in case you're using `@maverick-js/signals`). The examples are using a very basic setup for maverick-js and react: https://github.com/maxnowack/signaldb/blob/main/examples/rxdb/src/containers/App/List.tsx#L10-L17

I also wrote a blog post about how to integrate maverick-js, react and signaldb: https://dev.to/maxnowack/signaldb-and-maverick-signals-the-perfect-duo-for-reactivity-in-react-1p5a
