### ISSUE TITLE
createFilesystemAdapter does not work

### ISSUE THREAD

**Issue by angrocode** [maxnowack/signaldb#486]
```js
var cs = null, us = cs;
const W = /* @__PURE__ */ Zt(us);
function as(t) {
  let e = null;
  return {
    async register(n) {
      if (typeof window < "u")
        throw new Error("Filesystem adapter is not supported in the browser");
      await W.promises.access(t).then(() => !0).catch(() => !1) || await W.promises.writeFile(t, "[]"), W.watch(t, { encoding: "utf8" }, () => {
        n();
      });
    },
```
W.promises.access
Explain how this can bring back the promise

**Comment by maxnowack** [comment]
I'm not really sure what you mean. Maybe things clear up if you take a look at the unminified code: https://github.com/maxnowack/signaldb/blob/main/packages/signaldb/src/persistence/createFilesystemAdapter.ts#L9-L16

**Comment by angrocode** [comment]
When using esm Zt(us) returns null
W is null
W.promises.access can't work

**Comment by maxnowack** [comment]
It seems that the issue mentioned in #485 messed up the whole ESM format. Please try again with `v0.8.2`
