### ISSUE TITLE
Wrong import in SignalDB SolidJS Plugin

### ISSUE THREAD

**Issue by Blankeos** [maxnowack/signaldb#788]
Seems like there's a mistake here on the import. It should be importing from `"solid-js"`, not `"solidj-s/dist/solid"`

<img width="645" alt="image" src="https://github.com/maxnowack/signaldb/assets/38070918/1595397a-c542-4952-a269-430b2526fafc">

I confirmed that removing the `/dist/solid` fixes it.

Notice no errors:
<img width="607" alt="image" src="https://github.com/maxnowack/signaldb/assets/38070918/88888458-b9f3-49b0-8c85-9974b0c9024c">

**Comment by obedm503** [comment]
@Blankeos  See #701

**Comment by maxnowack** [comment]
Thanks @obedm503 for pointing to #701
The import of `solid-js/dist/solid` is used to make reactivity work on server side (see https://github.com/maxnowack/signaldb/issues/701#issuecomment-2096095138).
The question is, why it cannot find this module in your environment.

It's definitely in the npm package of `solid-js`:
<img width="442" alt="image" src="https://github.com/maxnowack/signaldb/assets/186073/b204645a-3a3d-4bd9-93a2-2f50fac0acae">

Which version on `solid-js` are you using? How does the `solid-js` folder look like in your `node_modules`?

**Comment by Blankeos** [comment]
Hi! Just realized there were replies on here. 

I'm on `"solid-js": "^1.8.17"` when I posted this.

How the solid-js folder looks like:

<img width="406" alt="image" src="https://github.com/maxnowack/signaldb/assets/38070918/08f0e31f-b8d5-442c-a755-317d7f421cda">

**Comment by maxnowack** [comment]
Okay, `dist/solid` is definitely in your `solid-js` module. I have no idea why the error occurs in your environment.

**Comment by maxnowack** [comment]
@Blankeos could you provide a minimal reproduction repo? I’ll try to solve it or find the root cause at least

**Comment by maxnowack** [comment]
Closing this, as no response received. Feel free to reopen the issue

**Comment by maxnowack** [comment]
The issue is finally resolved in `signaldb-plugin-solid@1.0.5` 🎉
