### ISSUE TITLE
How to replace a newly created row?

### ISSUE THREAD

**Issue by obedm503** [maxnowack/signaldb#792]
I'm dealing with a situation where I insert a skeleton row into a `ReplicatedCollection`. A skeleton row is a bare minimum that the server needs like an `id` and a `name`. The collection calls its `push` hook and the skeleton row gets sent to the server. The server then notifies all clients that a new row was created. This new row includes other fields added by the server like `createdAt`, `updatedAt`, and `createdBy`. The collection's `onChange` gets called with `{ added: [newCompleteRow], modified: [], removed: [] }`. My issue happens because the complete row added by `onChange` does not replace the initial skeleton row, and I end up with 2 rows with the same `id`.

There are a few possible solutions to my problem.

First, I could figure out if the current client is the one that initially inserted the skeleton row and swap the row (with `modified`) instead of simply adding it. I would rather not meddle with the backend.

The second option is that when `onChange` gets called with `added` rows, they should be upserted into the collection by the row's `id`. If a row is truly new it gets inserted otherwise it swaps the skeleton row.

A third option is to let the persistence adapter/replicated collection's `push`  hook have access to the collection object so I can manually `findOne` by `id` and swap the row if it already exists.

Any idea how to go about this?

**Comment by maxnowack** [comment]
Good catch!
I think upserting rows that were passed to `added` but already in the collection, is the most intuitive option.
Do you want to provide a PR or should I implement it?

**Comment by obedm503** [comment]
You would have a better idea of how to implement the fix than I. I'm not sure which files would need to change.

**Comment by maxnowack** [comment]
Okay! I'll work on that soon 🙂

**Comment by maxnowack** [comment]
Released in `v0.12.2` 🎉

**Comment by obedm503** [comment]
Thank you @maxnowack
