### ISSUE TITLE
Changeset issue causes collection to be emptied when using ReplicatedCollection (CombinePersistenceAdapter)

### ISSUE THREAD

**Issue by michaelkrog** [maxnowack/signaldb#835]
When using ReplicatedCollection with LocalStorageAdapter for persistence I am experiencing what I what describe as a timing issue. For the most part it work, but now and then the collection just empties itself.

I have tried to add a lot of logging to get to the bottom of it. Here is how it looks when it works fine.
<img width="1499" alt="Skærmbillede 2024-08-07 kl  13 27 58" src="https://github.com/user-attachments/assets/77bee6c6-2c9f-42b2-b31e-2674a7cd64ac">

You'll see that I am saving a new entity. Before I put it in the Collection I log the number of entities already in the collection. There are also log statements for when `persistence.pullCompleted` occurs, together with the current number of entities in the collection.

This is an example for when it breaks.
<img width="1505" alt="Skærmbillede 2024-08-07 kl  13 30 24" src="https://github.com/user-attachments/assets/ecb2dc82-30aa-4643-baa9-dd149dc76728">

Notice that `persistence.pullCompleted` happens twice, even if my pull method is only called once. Also in the last example the number of entities is 0, on the first `persistence.pullCompleted` event - before my pull method has returned a LoadResponse.

**Comment by michaelkrog** [comment]
If I remove the persistence it seems to work without any issue. Also the extra 'persistence.pullCompleted' event is gone.
<img width="1515" alt="Skærmbillede 2024-08-07 kl  13 58 52" src="https://github.com/user-attachments/assets/2c140ac0-7e28-4fa6-8406-6ef88f7f956c">

**Comment by michaelkrog** [comment]
@maxnowack If you want to, you can assign this one to me.

**Comment by michaelkrog** [comment]
I think I found the issue. It seems to specially be with combinePersistenceAdapter and LocalStorageAdapter in combination when a pull returns an empty changeset. 
```
{ changes: { added:[], modified:[], removed:[]}}
```

The combinePeristenceAdapter falls back to empty array if items are not specified.
https://github.com/maxnowack/signaldb/blob/ff762a17f4b1661923056378017dd04e27be13fa/packages/signaldb/src/persistence/combinePersistenceAdapters.ts#L64 

That empty array is then persisted if changes is empty.
https://github.com/maxnowack/signaldb/blob/ff762a17f4b1661923056378017dd04e27be13fa/packages/signaldb/src/persistence/createLocalStorageAdapter.ts#L17-L19


I'll try to add a test for it and a PR.

**Comment by maxnowack** [comment]
Thank you for digging into this! ❤️

**Comment by maxnowack** [comment]
Fix from #838 released in `v0.15.0` 🎉
