### ISSUE TITLE
Add an option to change the id field

### ISSUE THREAD

**Issue by jamesgibson14** [maxnowack/signaldb#855]
Most of my data is coming from Mongo, so I would like to use "_id" as the primary key in my signalDB colletions.
Maybe an options like "idField"?

**Comment by maxnowack** [comment]
Thanks for the suggestion! I see why you’d want to use _id as the primary key, but I’m concerned it might complicate the code a lot. So I'm unsure right now if we should to this.
Maybe there are some other options. I'm thinking about something like a server to client field mapping where fields can be renamed during pull/push.

**Comment by jamesgibson14** [comment]
Yes, I was looking through the code and "id" is used in a lot of places and
not really a simple change, I am trying to think of a different way to
handle it as well.

**Comment by maxnowack** [comment]
I'm closing this as not planned for now
