### ISSUE TITLE
Sprae framework

### ISSUE THREAD

**Issue by dy** [maxnowack/signaldb#858]
I wonder how would that be integrating signaldb with [sprae](https://github.com/dy/sprae)

**Comment by maxnowack** [comment]
It looks like sprae uses similar apis as preact or usignal. Keep it mind that this api doesn't have a way to do automatic cleanup or scope checking.
You can return a function from your effect that will be called on cleanup. Use this one to cleanup your cursors. You also must manually disable reactivity when making calls outside a reactive scope to avoid memory leaks. You can do this by passing `{ reactive: false }` to your options (e.g. `<collection>.find({ ... }, { reactive: false })`).
An adapter could be implemented like this:


### Adapter
````ts
import { signal } from 'sprae/signal'
import { createReactivityAdapter } from 'signaldb'

const reactivityAdapter = createReactivityAdapter({
  create: () => {
    const dep = signal(0)
    return {
      depend: () => {
        // eslint-disable-next-line @typescript-eslint/no-unused-expressions
        dep.value
      },
      notify: () => {
        dep.value = dep.peek() + 1
      },
    }
  },
  isInScope: undefined,
  onDispose: undefined,
})

export default reactivityAdapter
````

### Usage

````ts
import { effect } from 'sprae/signal'

const posts = new Collection({
  reactivity: reactivityAdapter,
})

effect(() => {
  const cursor = posts.find({ author: 'John' })
  console.log(cursor.count())
  return () => {
    cursor.cleanup()
  }
})
````
