### ISSUE TITLE
Reactivity(vue): Add failSilently to onScopeDispose

### ISSUE THREAD

**Issue by Cmacu** [maxnowack/signaldb#886]
When `signaldb` is used as part of basic Vue composition api store (declared outside of vue components) we get a warning in browser console:
```
[Vue warn] onScopeDispose() is called when there is no active effect scope to be associated with.
```
This warning would also show up anywhere `signaldb` is used outside of component context (ex: web workers, likely pinia, etc).

This can be resolved by adding `failSilently` to `onScopeDespose`:
https://github.com/vuejs/core/commit/9a936aaec489c79433a32791ecf5ddb1739a62bd

I can submit a PR for this.
I love this project btw. I've used dexie, electricSQL and tried RxDB. I think you have a very promising solution with same caveats (will submit issues when I get a chance).

**Comment by maxnowack** [comment]
Hi @Cmacu! Thanks!
I wasn’t aware of this parameter. Feel free to provide a PR if you want to contribute 🙂 

also don’t hesitate to open more issues! 😀

**Comment by maxnowack** [comment]
Not I looked a bit more into this. The warning you described is an indication that you haven't disabled reactivity in a case where it should be disabled (otherwise it [could lead to memory leaks](https://signaldb.js.org/reactivity/other/#isinscope-dependency-dependency-boolean)).
However I just saw that vue provides a [`getCurrentScope()`](https://vuejs.org/api/reactivity-advanced.html#getcurrentscope) method, that allows the implementation of automatic scope checking. 
With automatic scope checking, there is no need for the `failSilently` parameter anymore.

**Comment by Cmacu** [comment]
@maxnowack I am not sure I understand if that's something I need to fix on my end or something you are planning to implement.

Let me share a bit more context, which hopefully can make this easier. We have the following simplified singleton class:

```
// user.store.ts
class UserStore {
  private collection
  
  constructor() {
    this.collection = new ReplicatedCollection({
      pull: pullUsers,
      push: pushUsers,
      registerRemoteChange: socketListener,
      reactivity: vueReactivityAdapter,
      persistence: createLocalStorageAdapter('users'),
    });
  }

  listUsers() {
    return this.collection.find().fetch();
  }

  getUser(id: string) {
    return this.collection.findOne({ id });
  }

  createUser(user: User) {
    return this.collection.insert(user);
  }

  updateUser(id: string, user: User) {
    return this.collection.updateOne({ id }, { $set: user });
  }

  deleteUser(id: string) {
    return this.collection.removeOne({ id });
  }

}

export default new UserStore();
```

This store is than used in various places in the app:

```
// UsersPage.vue
<script setup lang="ts">
import userStore from 'user.store';

const users = computed(() => userStore.listUsers());

const deleteUser = (id: string) => userStore.deleteUser(id);
...
</script>

<template>
<ul>
   <li v-for="user in users" :key="user.id" class="flex">
    <a :href="`/user/${user.id}`">{{ user.name }}</a>
    <button @click="deleteUser(user.id)">Delete</button>
  </li>
</ul>
</template>  
```

This is a simplified version that would produce this error whenever navigate to another page. It's a solution I've used in the past with various other storage implementations without an issue.

**Comment by maxnowack** [comment]
I was thinking about extending the reactivity adapter for vue. Sorry for the confusion 😀 
#889 implements the changes I was talking about. Once they have been published, your error should go away 🙂

**Comment by maxnowack** [comment]
published in `signaldb-plugin-vue@1.1.0` 🎉

**Comment by maxnowack** [comment]
I noticed that `getCurrentScope()` didn't work as expected. I switched to adding `failSilently` to `onScopeDispose` as you suggested.

**Comment by Cmacu** [comment]
Yeah, I was going to point this out, but we were still investigating, if the issue was on our end.
Thanks for resolving it!
We are migrating to the Sync manager too! So exciting
