### ISSUE TITLE
Replication(proposal): Pull needs a way to get changes since last successful sync

### ISSUE THREAD

**Issue by Cmacu** [maxnowack/signaldb#888]
## Problem

In order to handle pull with `changes` properly we need to pass a timestamp to the backend identifying the starting point of the changes.

## Details

Unless I am missing something I don't see how the server would be able to identify which changes to send back other than sending all of them (which is covered via `items`). Usually this is done via `timestamp`. The problem with implementing timestamp within the pull function is that we also need a way to verify that the sync was successful. This timestamp would also need to be stored somewhere in case of re-establishing a session. 

## Proposals

- [ ] A: Store successful sync timestamp internally in `signaldb` and pass it to the pull function. This would require some type of internal storage/configuration to maintain the timestamps for each collection. This solution would be great if there are other instances where `signaldb` needs to preserve some configuration data (encryption keys, index labels, timezone/internationalization config, etc). 
- [ ] B: Provide `collection.on('pull.success')` hook that can be used to handle the timestamp persistence in devland. This might be a simpler solution, but also allows more room for error and needs to be documented well. The key here is that the timestamp needs to be established at the start of the `pull` call and stored when the hook is triggered to missing some gaps in between the 2 events.
- [ ] C: There is `collection.on('persistance.error')`, but this error seams to also be triggered in various scenarios outside of `push/pull` scope. Setting up dedicated `collection.on('pull.error')` could be helpful, but not as much as option B. 
- [ ] D: This can be handled in devland by adding `syncedAt` property on the collection items and getting the last syncedAt to be used as a timestamp. This would have performance impact on large collections.

## Caveats

It would be wise to consider/document what happens whenever storing pull changes was not successful. In such case there is discrepancy/conflict between the local and remote data. Some guidance/strategy/links would go a long way to mitigate some of the common issues developers would run into trying to use `signaldb`.

## Relevant Docs

- replication: https://signaldb.js.org/replication/#replicatedcollection
- events: https://signaldb.js.org/collections/#events

Happy to discuss any of the above here or via other channels.

**Comment by maxnowack** [comment]
I‘m currently working on a totally new approach for the replication. It will be a lot more powerful compared with the current one and also has a conflict resolution implemented. 
There is also a way to get informations about the last successful sync during pull. 
let‘s discuss it further once my PR with the new approach is ready 🙂

**Comment by Cmacu** [comment]
@maxnowack sounds great! Let me know, if there is anything I can do to help. I've been looking into some of the internals and I am very impressed with your work on signaldb. You are an inspiration!

**Comment by maxnowack** [comment]
@Cmacu I've just opened #893 with a draft of the new sync/replication approach. Feel free to leave some feedback 🙂 
As I'm already saving some meta information like the sync status in the `SyncManager`, It should be really straight forward to make them available in the `pull` and `push` methods.

Another thing that came into my mind regarding the original issue was that the server and client time can differ. So it might be necessary to *synchonize* the timestamp before sending it to the server. This could be done like in [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol#Clock_synchronization_algorithm).

**Comment by maxnowack** [comment]
resolved in #893
