### ISSUE TITLE
Reactivity(vue): v0.20 regression/bug

### ISSUE THREAD

**Issue by Cmacu** [maxnowack/signaldb#931]
After upgrading to v0.20 and implementing the sync manager I noticed that the reactivity stopped working.

Not sure it matters, but we are using computed instead of watchEffect (which I also tried)

Vue reactivity works fine in v0.18. I can work on setting up minimal reproduction, if that would help.

**Comment by maxnowack** [comment]
Which version of `signaldb-plugin-vue` are you using?. A minimal reproduction would be great! 🙂

**Comment by Cmacu** [comment]
@maxnowack here is a reproduction of the issue: https://github.com/Cmacu/signaldb-sync/blob/main/src/App.vue
This is a basic `npm create vue@latest` app with simple user collection persisted in local storage.
Here is also a gif illustrating the issue:
![signaldb-reactivity-issue](https://github.com/user-attachments/assets/46d49e1d-aed2-4106-8eca-983ce79dbf1f)

**Comment by Cmacu** [comment]
We are using the latest `signaldb-plugin-vue` version. Trying prior versions didn't make a difference.

**Comment by maxnowack** [comment]
It looks like there was an issue while I've published a new version of `signaldb-plugin-vue`. Somehow the old code was published. Please try `signaldb-plugin-vue@1.1.2`. This version should work 🙂
