### ISSUE TITLE
Solid scope check

### ISSUE THREAD

**Issue by obedm503** [maxnowack/signaldb#938]
Right now `signaldb-plugin-solid` does not support reactive scope checking and automatic cleanup. Would Solid's [`getOwner`](https://docs.solidjs.com/reference/reactive-utilities/get-owner) function solve this? `getOwner` returns the current reactive scope or null if outside one.

The plugin could be changed to this:
```ts
import { createReactivityAdapter } from 'signaldb'
import { createSignal, getOwner,  onCleanup } from 'solid-js'

const solidReactivityAdapter = createReactivityAdapter({
  create: () => {
    const [depend, rerun] = createSignal(undefined, { equals: false })
    return {
      depend: () => {
        depend()
      },
      notify: () => {
        rerun()
      },
    }
  },
  isInScope: () => !!getOwner(),
  onDispose: (callback) => {
    onCleanup(callback)
  },
})

export default solidReactivityAdapter
```

I've been playing with the new `SyncManager` with solid and noticed a ton of warnings from solid about `onCleanup` not getting called. This change seems to fix those warnings.

There is one possible issue with this. The solid docs mention:
> Note that the owning reactive scope isn't necessarily tracking. For example, untrack turns off tracking for the duration of a function (without creating a new reactive scope), as do components created via JSX (`<Component ...>`).

Is there a way to test if `getOwner` would actually fix this issue?

**Comment by maxnowack** [comment]
Thanks, that sound like a solution! 🙂 I think I've overseen this in the docs.

> There is one possible issue with this. The solid docs mention:
> 
> > Note that the owning reactive scope isn't necessarily tracking. For example, untrack turns off tracking for the duration of a function (without creating a new reactive scope), as do components created via JSX (`<Component ...>`).

I don't think that this is an issue in our case as we only scope **if** a scope is present and it doesn't make difference which scope exactly it is.
 
> Is there a way to test if `getOwner` would actually fix this issue?

You could use you code as a reactivity adapter to test if everything works:
```js
const collection  = new Collection({
  reactivity: createReactivityAdapter({
    create: () => {
      const [depend, rerun] = createSignal(undefined, { equals: false })
      return {
        depend: () => {
          depend()
        },
        notify: () => {
          rerun()
        },
      }
    },
    isInScope: () => !!getOwner(),
    onDispose: (callback) => {
      onCleanup(callback)
    },
  }),
})
```

It would be awesome if you could create a PR after your tests were successful 🙂
