### ISSUE TITLE
`SyncManager` fails to find the `lastFinishedSync` when using an async persistence adapter

### ISSUE THREAD

**Issue by obedm503** [maxnowack/signaldb#943]
The `SyncManager` fails to find the `lastFinishedSync` when using an async persistence adapter when attempting to start sync soon after creation. This issue only happens with async persistence adapters that might take several ms loading data like an [`indexeddb persister`](https://github.com/obedm503/trellix-offline/blob/8dbe7d46e2774ded0bfbf3a75fdaa9bf9d2a32d7/signaldb/src/idb-persister.ts) and not with sync persisters like local storage.

```ts
const syncManager = new SyncManager({  
  persistenceAdapter: (id) => idbPersister(id),
  pull: async ({ name, lastFinishedSyncEnd }) => {
    // lastFinishedSyncEnd is always undefined on the first sync
    const response = await fetch(`/api/collections/${collectionOptions.name}?since=${lastFinishedSyncStart}`)
    return await response.json()
  },
  // ...
})
 
const collection = new Collection()
syncManager.addCollection(collection, {
  name: 'todos',
})
 
syncManager.sync('todos') // will always load all the data instead of just data since `lastFinishedSyncEnd`
```

My [current workaround](https://github.com/obedm503/trellix-offline/blob/12a41ba6fe7c49b9c2b5a732a07c469c2c5de744/signaldb/src/collections.tsx#L139-L166) is to delay calling `sync` or `syncAll` until `syncManager.syncOperations`, `syncManager.changes`, `syncManager.remoteChanges`, and `syncManager.snapshots` have all emitted the `persistence.pullCompleted` event once. This is not ideal because I'm using private properties. Ideally, the sync manager would emit some type of `ready` or `init` event once its internal collections have all loaded into memory.

**Comment by maxnowack** [comment]
I've just opened #949 
With this PR, the SyncManager waits until the persistence adapters of the internal collections are ready before the sync starts
