### ISSUE TITLE
sync(registerRemoteChange): still getting onChange as first argument after updating to v0.21.2

### ISSUE THREAD

**Issue by Cmacu** [maxnowack/signaldb#987]
The following code returns the onChange as first argument:

```
...
registerRemoteChange: (collection, onChange) => {
    console.error('sync registerRemoteChange', collection, onChange)
    socket.connection.on(`sync-${collection.name}`, onChange)
}
```

![Screenshot 2024-09-27 at 5 16 39 PM](https://github.com/user-attachments/assets/73ea14ec-d5ef-4f8b-a1e9-afd4f4145eb8)

And I triple checked the version to make sure. Even the types show up as expected:

![Screenshot 2024-09-27 at 5 23 47 PM](https://github.com/user-attachments/assets/6c2a7f94-568f-47a0-9d35-4d85d391fb50)

Maybe there is some issue with the build or deployment script?

**Comment by maxnowack** [comment]
I've just took a look at the cod that is in the npm package and it seems correct:
<img width="764" alt="image" src="https://github.com/user-attachments/assets/dc002489-4d10-4443-97cc-221518158c3f">

**Comment by maxnowack** [comment]
This should be resolved in the meantime if there was an issue in `v0.21.2`. Please reopen if there is still something wrong 🙂
